services:
    spring.merit_autogroup.autogroups.type.merit:
        class: spring\merit_autogroup\conditions\type\merit
        scope: prototype
        arguments:
            - @service_container
            - @dbal.conn
            - @user
            - %core.table_prefix%autogroups_rules
            - %core.table_prefix%autogroups_types
            - %core.root_path%
            - %core.php_ext%
        tags:
            - { name: phpbb.autogroups.type }
